import { useState } from 'react'
import {
  Box, Typography, Grid, Card, CardContent, Stack, ToggleButtonGroup, ToggleButton, TextField,
  Alert, Slider, Divider, Chip, Button, Snackbar,
} from '@mui/material'
import SettingsRoundedIcon from '@mui/icons-material/SettingsRounded'
import AutoAwesomeRoundedIcon from '@mui/icons-material/AutoAwesomeRounded'
import MemoryRoundedIcon from '@mui/icons-material/MemoryRounded'
import { useApp } from '../context/AppContext.jsx'

export default function Settings() {
  const { settings, setSettings } = useApp()
  const [saved, setSaved] = useState(false)

  const update = (patch) => setSettings((s) => ({ ...s, ...patch }))

  return (
    <Box>
      <Stack direction="row" spacing={1.5} alignItems="center" sx={{ mb: 1 }}>
        <SettingsRoundedIcon color="primary" />
        <Typography variant="h4">Settings</Typography>
      </Stack>
      <Typography color="text.secondary" sx={{ mb: 3 }}>
        Configure the orchestration engine, policies, and platform defaults.
      </Typography>

      <Grid container spacing={2.5}>
        <Grid item xs={12} md={7}>
          <Card><CardContent>
            <Stack direction="row" spacing={1} alignItems="center" sx={{ mb: 2 }}>
              <AutoAwesomeRoundedIcon color="secondary" />
              <Typography variant="h6">AI configuration engine</Typography>
            </Stack>
            <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
              Choose how CortexIE turns requests into provisioning plans.
            </Typography>

            <ToggleButtonGroup exclusive value={settings.aiMode} onChange={(_, v) => v && update({ aiMode: v })} sx={{ mb: 2 }}>
              <ToggleButton value="rule" sx={{ px: 3 }}>
                <Stack alignItems="flex-start">
                  <Typography fontWeight={700}>Rule-based</Typography>
                  <Typography variant="caption" color="text.secondary">Offline · deterministic</Typography>
                </Stack>
              </ToggleButton>
              <ToggleButton value="claude" sx={{ px: 3 }}>
                <Stack alignItems="flex-start">
                  <Typography fontWeight={700}>Claude API</Typography>
                  <Typography variant="caption" color="text.secondary">claude-opus-4-8</Typography>
                </Stack>
              </ToggleButton>
            </ToggleButtonGroup>

            {settings.aiMode === 'claude' ? (
              <>
                <Alert severity="info" icon={<MemoryRoundedIcon />} sx={{ mb: 2 }}>
                  Plans are generated by Claude (structured JSON output). Enter an API key below. If the call fails,
                  CortexIE automatically falls back to the rule-based engine so the demo never breaks.
                </Alert>
                <TextField
                  fullWidth type="password" label="Anthropic API key"
                  placeholder="sk-ant-..."
                  value={settings.apiKey}
                  onChange={(e) => update({ apiKey: e.target.value })}
                  helperText="Stored in-memory only (prototype). For production, proxy calls through a backend — never ship keys to the browser."
                />
              </>
            ) : (
              <Alert severity="success">
                Rule-based engine active. No API key required — works fully offline. Great for reliable demos.
              </Alert>
            )}
          </CardContent></Card>
        </Grid>

        <Grid item xs={12} md={5}>
          <Card sx={{ mb: 2.5 }}><CardContent>
            <Typography variant="h6" sx={{ mb: 1 }}>Auto-cleanup policy</Typography>
            <Typography variant="body2" color="text.secondary">Reap idle sandboxes after</Typography>
            <Box sx={{ px: 1, mt: 2 }}>
              <Slider
                value={settings.autoCleanupHours}
                onChange={(_, v) => update({ autoCleanupHours: v })}
                step={12} marks min={12} max={168}
                valueLabelDisplay="on" valueLabelFormat={(v) => `${v}h`}
              />
            </Box>
            <Typography variant="caption" color="text.secondary">
              Idle environments are paused, then terminated after {settings.autoCleanupHours} hours.
            </Typography>
          </CardContent></Card>

          <Card><CardContent>
            <Typography variant="h6" sx={{ mb: 1 }}>Platform</Typography>
            <Stack spacing={1.5}>
              <Stack direction="row" justifyContent="space-between"><Typography color="text.secondary">Version</Typography><Chip size="small" label="CortexIE 0.1.0" variant="outlined" /></Stack>
              <Divider />
              <Stack direction="row" justifyContent="space-between"><Typography color="text.secondary">Your role</Typography><Chip size="small" label={settings.role} color="secondary" /></Stack>
              <Divider />
              <Stack direction="row" justifyContent="space-between"><Typography color="text.secondary">Default cloud</Typography><Typography variant="body2">Azure · eastus2</Typography></Stack>
            </Stack>
          </CardContent></Card>
        </Grid>

        <Grid item xs={12}>
          <Stack direction="row" justifyContent="flex-end">
            <Button variant="contained" onClick={() => setSaved(true)}>Save settings</Button>
          </Stack>
        </Grid>
      </Grid>

      <Snackbar open={saved} autoHideDuration={2500} onClose={() => setSaved(false)} message="Settings saved" anchorOrigin={{ vertical: 'bottom', horizontal: 'center' }} />
    </Box>
  )
}
